---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aws
  namespace: prometheus
spec:
  hard:
    storagens2.storageclass.storage.k8s.io/requests.storage: 0