apiVersion: v1
kind: Service
metadata:
  name: web-prometheus-server
  labels:
    app: prometheus-server
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
  - name: http
    port: 90
    targetPort: 9090
    protocol: TCP