apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: search-deploy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-deploy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50 
