--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql-deployment
spec: 
  selector: 
    matchLabels: 
      app: mysql
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: root-password
                  name: mysql-secrets
            - 
              name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: admin-password
                  name: mysql-secrets
          envFrom: 
            - 
              configMapRef: 
                name: mysql-configmap
          image: "mysql:5.7"
          name: mysql
          args:
          - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          ports: 
            - 
              containerPort: 3306
              name: mysql
          volumeMounts: 
            - 
              mountPath: /var/lib/mysql
              name: mysql-pv
      volumes: 
        - 
          name: mysql-pv
          persistentVolumeClaim: 
            claimName: clarus-pv-claim
--- 
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec: 
  ports: 
    - 
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector: 
    app: mysql
  type: ClusterIP
